### ISSUE TITLE
"exit" context

### ISSUE THREAD

**Issue by flbla** [sbstp/kubie#119]
Hello,
could be great to "exit" context.
probably something that unset all kubie variables and unset the kubie prompt.

**Comment by mckennajones** [comment]
@flbla in my experience simply executing `exit` does exactly that. It pulls you out of the shell that kubie created. For example:
```
➜  ~ k8s:(kind-kind) kubie ctx mr-play-A
➜  ~ k8s:(mr-play-A) echo $KUBECONFIG
/var/folders/lf/w86pqkpx7sj8njk569cdggw80000gn/T/kubie-configNvlDLh.yaml
➜  ~ k8s:(mr-play-A) exit
➜  ~ k8s:(kind-kind) echo $KUBECONFIG

➜  ~ k8s:(kind-kind)
```
