### ISSUE TITLE
Please support nushell

### ISSUE THREAD

**Issue by brianmay** [sbstp/kubie#121]
nushell is available here: https://www.nushell.sh/

```
$ kubie ctx
Error: Could not detect shell in use
```

**Comment by Miuler** [comment]
Please, add support for nushel :(

**Comment by Miuler** [comment]
Resolved in #130

**Comment by Miuler** [comment]
The binary for impatient people, because the pull requests are taking a long time.

https://github.com/Miuler/kubie/releases/tag/v0.20.0

https://github.com/Miuler/kubie/releases/download/v0.20.0/kubie

**Comment by Miuler** [comment]
What happened?
