### ISSUE TITLE
v0.20.0 darwin binary does not released

### ISSUE THREAD

**Issue by mugioka** [sbstp/kubie#133]
<img width="1071" alt="image" src="https://github.com/sbstp/kubie/assets/62197019/26d08326-deb2-41c0-9cf2-1e17f0576b43">

release workflow seems to be queued to github actions.

**Comment by sbstp** [comment]
Not sure what's going on... MacOS runners aren't picking up the job

**Comment by mugioka** [comment]
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

This may not be relevant to this issue, but it looks like the macOS runner 10-15 will be gone in a few months.

**Comment by sbstp** [comment]
Thanks for finding that out. It seems like that's the issue indeed

**Comment by sbstp** [comment]
v0.20.1 should be out soon

**Comment by mugioka** [comment]
```
❯ kubie -V
kubie 0.20.1
```

I installed kubie(v0.20.1) successfully!!
Thanks for the quick response.
