### ISSUE TITLE
shell spawning issue with kubie 0.15.2

### ISSUE THREAD

**Issue by tuxtof** [sbstp/kubie#91]
Since upgrade to kubie 0.15.2 my kubie ctx command failed with

/var/folders/g3/t0x1k_1d3_g9jqwr4nt67fkw0000gn/T/.tmpsP4WBJ/.zshrc:source:28: too many open files: /etc/zprofile
/var/folders/g3/t0x1k_1d3_g9jqwr4nt67fkw0000gn/T/.tmpsP4WBJ/.zshrc:source:38: too many open files: /etc/zshrc
/var/folders/g3/t0x1k_1d3_g9jqwr4nt67fkw0000gn/T/.tmpsP4WBJ/.zshrc:source:44: too many open files: /var/folders/g3/t0x1k_1d3_g9jqwr4nt67fkw0000gn/T/.tmpsP4WBJ/.zshrc

i try to reset my entire zsh env , same issue
i try on an entire new mac same issue

downgrade to 0.15.1 solve the problem

i'm using macOS 12.0.1 with default shell

**Comment by sbstp** [comment]
@c10l maybe you have an idea why this is happening?

**Comment by c10l** [comment]
Huh, sorry. I am an idiot. I will send a PR in a bit with a fix.
